"""empty message

Revision ID: e8fc970c97ac
Revises: 2f4a8cf1505a
Create Date: 2021-04-21 15:07:57.919792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8fc970c97ac'
down_revision = '2f4a8cf1505a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'authority_contact',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'authority_contact',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
